### PR TITLE
Create E.py ang G.py

### PR DESCRIPTION
**Pull request by vinayak42**

### CODE REVIEW

**Comment by splucs** [comment]
@vinayak42 can you link the codeforces submissions to confirm the are accepted?

**Comment by vinayak42** [comment]
Link to E: https://codeforces.com/gym/100513/submission/62361139 
Link to G: https://codeforces.com/gym/100513/submission/62353295

**Comment by splucs** [comment]
@vinayak42 it seems I can't access the link. Can you provide prints of the verdict?

**Comment by splucs** [comment]
@vinayak42 I'll consider your comment as confirmation of Accepted, merging.

**Pull request merged**
